name: Docker Image CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Login to Scaleway Container Registry
      uses: docker/login-action@v3
      with:
        username: nologin
        password: ${{ secrets.SCALEWAY_API_KEY }}
        registry: ${{ secrets.CONTAINER_REGISTRY_ENDPOINT }}
    - name: Build the Docker image
      run: docker build . -t ${{ secrets.CONTAINER_REGISTRY_ENDPOINT }}/moise
    - name: Push the Docker Image
      run: docker push ${{ secrets.CONTAINER_REGISTRY_ENDPOINT }}/moise

  deploy:
      runs-on: ubuntu-latest
      needs: [build-image]
      steps:
        - name: Deploy app
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.SCALEWAY_HOST }}
            username: ${{ secrets.SCALEWAY_USER }}
            key: ${{ secrets.SCALEWAY_SSH_KEY }}
            port: 22
            # stop, remove and update step by step
            script: |
              #cd ./bienvenu
              docker stop moise || true
              docker rm moise || true
              docker pull ${{ secrets.CONTAINER_REGISTRY_ENDPOINT }}/moise
              docker run -d --name moise -p 8001:8506 ${{ secrets.CONTAINER_REGISTRY_ENDPOINT }}/moise




